Use strsafe.h + StringCchPrintf unconditionally.
Many years ago MinGW lacked the header and function.  However they are
both present now.  (They've both been present in Windows since XP SP2.)
Use them unconditionally.

This also avoids a probably bogus error which occurred with MinGW +
snwprintf:

In file included from /usr/i686-w64-mingw32/sys-root/mingw/include/_mingw.h:10,
                 from /usr/i686-w64-mingw32/sys-root/mingw/include/windows.h:9,
                 from RHSrvAny.c:28:
In function 'snwprintf',
    inlined from 'SvcInit' at RHSrvAny.c:385:5,
    inlined from 'SvcMain' at RHSrvAny.c:294:5:
/usr/i686-w64-mingw32/sys-root/mingw/include/stdio.h:1124:3: error: call to '__mingw_chk_fail_warn' declared with attribute warning: Buffer overflow detected [-Werror=attribute-warning]
 1124 |   __mingw_bos_ptr_chk_warn(__stream, __n * sizeof(wchar_t), 1);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors